run:
	java -cp bin Main

build:
	javac -d bin Main.javac
	
clean:
	rm -r bin

git:
	git config --global user.name "Tinais24"
	git config --global user.email "urtzigurkewicz@outlook.com"

testAula04:
	#Compilando arquivo de teste
	javac -d bin test/testAula04.java 
	
	#Executando teste
	java -cp bin TestAula04